# Generated by Django 5.2.1 on 2026-03-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', help_text='???', max_length=10),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='course_type',
            field=models.CharField(choices=[('monthly', '????'), ('holiday', '????'), ('yearly', '????')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='date',
            field=models.DateField(help_text='????'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='location',
            field=models.CharField(help_text='????', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='teacher',
            field=models.CharField(help_text='????', max_length=100),
        ),
    ]
