# Generated by Django 5.2.1 on 2026-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursepage_weekday_alter_coursepage_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='course_type',
            field=models.CharField(choices=[('monthly', '按月课程'), ('holiday', '假期课程'), ('yearly', '一年课程')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='date',
            field=models.DateField(help_text='开课日期'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='location',
            field=models.CharField(help_text='上课地点', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='teacher',
            field=models.CharField(help_text='教师姓名', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', help_text='星期几', max_length=10),
        ),
    ]
