# Generated by Django 5.2.1 on 2026-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursepage_course_type_alter_coursepage_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='course_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('holiday', 'Holiday'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
