# Generated by Django 5.2.1 on 2026-03-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursepage_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
