# Generated by Django 5.2.1 on 2026-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursepage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='适合年龄', null=True),
        ),
    ]
