# Generated by Django 5.2.1 on 2026-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursepage_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='age',
            field=models.CharField(blank=True, help_text='适合年龄（例如：10-12）', max_length=50, null=True),
        ),
    ]
