# Generated by Django 5.2.1 on 2025-05-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('portfolio', '0008_cryptoindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='credit_cards_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.ceditcardsindexpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='crypto_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.cryptoindexpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='p2p_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.p2pindexpage'),
        ),
    ]
