# Generated by Django 5.2.1 on 2026-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_credit_cards_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_kicker',
            field=models.CharField(default='Pop Art N Craft', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_primary_image',
            field=models.CharField(blank=True, default='/static/images/bitfinex-logo.webp', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_primary_image_alt',
            field=models.CharField(default='Bitfinex', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_primary_label',
            field=models.CharField(default='Bitfinex', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_primary_url',
            field=models.URLField(blank=True, default='/bitfinex/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_secondary_image',
            field=models.CharField(blank=True, default='/static/images/awepaylogo_pay_al.png', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_secondary_image_alt',
            field=models.CharField(default='Awesomepay', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_secondary_label',
            field=models.CharField(default='Awesomepay', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_secondary_url',
            field=models.URLField(blank=True, default='/awesome/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='About Us', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='credit_cta_label',
            field=models.CharField(default='Let go!', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='credit_cta_url',
            field=models.URLField(blank=True, default='/credit-cards/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='credit_kicker',
            field=models.CharField(default='Pop Art N Craft', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='credit_title',
            field=models.CharField(default='Products', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_credit_label',
            field=models.CharField(default='CREDIT CARD', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_credit_url',
            field=models.URLField(blank=True, default='/credit-cards/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_label',
            field=models.CharField(default='CRYPTO', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_primary_image',
            field=models.CharField(blank=True, default='/static/images/bitfinex-logo.webp', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_primary_image_alt',
            field=models.CharField(default='Bitfinex', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_primary_label',
            field=models.CharField(default='Bitfinex', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_primary_url',
            field=models.URLField(blank=True, default='/bitfinex/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_secondary_image',
            field=models.CharField(blank=True, default='/static/images/awepaylogo_pay_al.png', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_secondary_image_alt',
            field=models.CharField(default='Awesomepay', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_secondary_label',
            field=models.CharField(default='Awesomepay', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_crypto_secondary_url',
            field=models.URLField(blank=True, default='/awesome/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_kicker',
            field=models.CharField(default='Welcome to', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_p2p_label',
            field=models.CharField(default='P2P', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_p2p_url',
            field=models.URLField(blank=True, default='/p2p/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_title',
            field=models.CharField(default='Pop Art N Craft', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='p2p_cta_label',
            field=models.CharField(default='Let go!', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='p2p_cta_url',
            field=models.URLField(blank=True, default='/p2p/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='p2p_kicker',
            field=models.CharField(default='Pop Art N Craft', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='p2p_title',
            field=models.CharField(default='Art Class', max_length=200),
        ),
    ]
