# Generated by Django 5.2.1 on 2026-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_about_kicker_homepage_about_primary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_primary_url',
            field=models.CharField(blank=True, default='/bitfinex/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_secondary_url',
            field=models.CharField(blank=True, default='/awesome/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='credit_cta_url',
            field=models.CharField(blank=True, default='/credit-cards/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_credit_url',
            field=models.CharField(blank=True, default='/credit-cards/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_crypto_primary_url',
            field=models.CharField(blank=True, default='/bitfinex/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_crypto_secondary_url',
            field=models.CharField(blank=True, default='/awesome/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_p2p_url',
            field=models.CharField(blank=True, default='/p2p/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='p2p_cta_url',
            field=models.CharField(blank=True, default='/p2p/', max_length=255),
        ),
    ]
