# Generated by Django 5.2.1 on 2026-03-04 07:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_about_primary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_sections',
            field=wagtail.fields.StreamField([('intro_section', 16), ('feature_section', 27)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('intro', 'intro')]}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome to', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Pop Art N Craft', 'max_length': 200, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'P2P', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'default': '/p2p/', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'CREDIT CARD', 'max_length': 100, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'default': '/credit-cards/', 'max_length': 255, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'CRYPTO', 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Bitfinex', 'max_length': 100, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'default': '/bitfinex/', 'max_length': 255, 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'default': '/static/images/bitfinex-logo.webp', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Bitfinex', 'max_length': 120, 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Awesomepay', 'max_length': 100, 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'default': '/awesome/', 'max_length': 255, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'default': '/static/images/awepaylogo_pay_al.png', 'max_length': 255, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Awesomepay', 'max_length': 120, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('section_class', 0), ('kicker', 1), ('title', 2), ('p2p_label', 3), ('p2p_url', 4), ('credit_label', 5), ('credit_url', 6), ('crypto_label', 7), ('crypto_primary_label', 8), ('crypto_primary_url', 9), ('crypto_primary_image', 10), ('crypto_primary_image_alt', 11), ('crypto_secondary_label', 12), ('crypto_secondary_url', 13), ('crypto_secondary_image', 14), ('crypto_secondary_image_alt', 15)]], {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('p2p', 'p2p'), ('creditcard', 'creditcard'), ('crypto', 'crypto')]}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Pop Art N Craft', 'max_length': 100, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': '例如: p2p-line', 'max_length': 120, 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': '例如: /static/images/bitfinex-logo.webp', 'max_length': 255, 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('label', 20), ('url', 21), ('icon_class', 22), ('image_url', 23), ('image_alt', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'max_num': 4, 'min_num': 1}), 27: ('wagtail.blocks.StructBlock', [[('section_class', 17), ('kicker', 18), ('title', 19), ('links', 26)]], {})}),
        ),
    ]
