# Generated by Django 5.2.1 on 2026-03-04 08:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_home_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_sections',
            field=wagtail.fields.StreamField([('intro_section', 11), ('feature_section', 16)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('intro', 'intro')]}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome to', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Pop Art N Craft', 'max_length': 200, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': '例如: p2p-line', 'max_length': 120, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': '例如: /static/images/bitfinex-logo.webp', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 3), ('url', 4), ('icon_class', 5), ('image_url', 6), ('image_alt', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': '顶部主链接（例如 P2P / CREDIT CARD / CRYPTO），可增删和排序。', 'required': False}), 10: ('wagtail.blocks.ListBlock', (8,), {'help_text': '次级链接（例如 Bitfinex / Awesomepay），可增删和排序。', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('section_class', 0), ('kicker', 1), ('title', 2), ('main_links', 9), ('sub_links', 10)]], {}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('p2p', 'p2p'), ('creditcard', 'creditcard'), ('crypto', 'crypto')]}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Pop Art N Craft', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 15: ('wagtail.blocks.ListBlock', (8,), {'max_num': 4, 'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('section_class', 12), ('kicker', 13), ('title', 14), ('links', 15)]], {})}),
        ),
    ]
