# Generated by Django 5.2.1 on 2026-03-04 08:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_about_kicker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_sections',
            field=wagtail.fields.StreamField([('intro_section', 12), ('feature_section', 18)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('intro', 'intro')]}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Home', 'help_text': '底部导航显示文字（timeline）。', 'max_length': 80, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome to', 'max_length': 100, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Pop Art N Craft', 'max_length': 200, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': '例如: p2p-line', 'max_length': 120, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': '例如: /static/images/bitfinex-logo.webp', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('icon_class', 6), ('image_url', 7), ('image_alt', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': '顶部主链接（例如 P2P / CREDIT CARD / CRYPTO），可增删和排序。', 'required': False}), 11: ('wagtail.blocks.ListBlock', (9,), {'help_text': '次级链接（例如 Bitfinex / Awesomepay），可增删和排序。', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('section_class', 0), ('menu_label', 1), ('kicker', 2), ('title', 3), ('main_links', 10), ('sub_links', 11)]], {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('p2p', 'p2p'), ('creditcard', 'creditcard'), ('crypto', 'crypto')]}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Section', 'help_text': '底部导航显示文字（timeline）。', 'max_length': 80, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Pop Art N Craft', 'max_length': 100, 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 17: ('wagtail.blocks.ListBlock', (9,), {'max_num': 4, 'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('section_class', 13), ('menu_label', 14), ('kicker', 15), ('title', 16), ('links', 17)]], {})}),
        ),
    ]
