# Generated by Django 5.2.1 on 2026-03-09 08:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_home_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_sections',
            field=wagtail.fields.StreamField([('intro_section', 14)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('intro', 'intro')]}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Home', 'help_text': 'Text shown in bottom timeline navigation.', 'max_length': 80, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': '/static/images/333.jpg', 'help_text': 'Background image URL fallback (optional).', 'max_length': 255, 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload a background image (recommended size: 2163x1080).', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome to', 'max_length': 100, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Pop Art N Craft', 'max_length': 200, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select an internal page.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Custom URL, e.g. /our-product/ or https://example.com', 'max_length': 255, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: p2p-line', 'max_length': 120, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: /static/images/bitfinex-logo.webp', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 6), ('page', 7), ('custom_url', 8), ('icon_class', 9), ('image_url', 10), ('image_alt', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Top main links; you can add, remove, and reorder.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('section_class', 0), ('menu_label', 1), ('background_image_url', 2), ('background_image', 3), ('kicker', 4), ('title', 5), ('main_links', 13)]], {})}),
        ),
    ]
