# Generated by Django 5.2.1 on 2025-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomepayinpage',
            name='code_block',
            field=models.TextField(blank=True),
        ),
    ]
