# Generated by Django 5.2.1 on 2025-05-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_awesomepayinpage_code_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomeindexpage',
            name='code_block',
            field=models.TextField(blank=True),
        ),
    ]
