# Generated by Django 5.2.1 on 2025-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_bitfinexpayinsectionpage_bitfinexpayinsubsectionpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitfinexindexpage',
            name='code_block',
            field=models.TextField(blank=True),
        ),
    ]
