# Generated by Django 5.2.1 on 2025-05-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_sectionpage_subsectionpage_tabpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awesomepayinsectionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='awesomepayinsubsectionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='awesomepayoutpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='awesomepayoutsectionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='awesomepayoutsubsectionpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AwesomePayInPage',
        ),
        migrations.DeleteModel(
            name='AwesomePayInSectionPage',
        ),
        migrations.DeleteModel(
            name='AwesomePayInSubsectionPage',
        ),
        migrations.DeleteModel(
            name='AwesomePayOutPage',
        ),
        migrations.DeleteModel(
            name='AwesomePayOutSectionPage',
        ),
        migrations.DeleteModel(
            name='AwesomePayOutSubsectionPage',
        ),
    ]
