# Generated by Django 5.2.1 on 2025-06-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_productindexpage_productpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitfinexindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='creditcardsindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='cryptoindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='p2pindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='sectionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='subsectionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='tabpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AwesomeIndexPage',
        ),
        migrations.DeleteModel(
            name='BitfinexIndexPage',
        ),
        migrations.DeleteModel(
            name='CreditCardsIndexPage',
        ),
        migrations.DeleteModel(
            name='CryptoIndexPage',
        ),
        migrations.DeleteModel(
            name='P2PIndexPage',
        ),
        migrations.DeleteModel(
            name='SectionPage',
        ),
        migrations.DeleteModel(
            name='SubsectionPage',
        ),
        migrations.DeleteModel(
            name='TabPage',
        ),
    ]
